name: Build and Deploy Spring Boot App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
    
      - name: Grant execute permission for gradle
        run: chmod +x ./gradlew

      - name: Build to Boot Project
        run: ./gradlew bootJar -x test

      - name: Verify Build jar
        run: |
          if [ ! -f build/libs/*.jar ]; then
            echo "빌드 실패"
            exit 1
          fi
          echo "빌드파일 만들기 성공"

      - name: Change Maintenance Mode
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/deploy
            sudo cp /home/ubuntu/deploy/front/dist/index.html /home/ubuntu/deploy/front/maintenence/index_tmp.html
            sudo cp /home/ubuntu/deploy/front/maintenence/index.html /home/ubuntu/deploy/front/dist/index.html
            docker compose restart web
            echo "유지보수 모드 활성화"
            sleep 5

      - name: Prepare Target Directory
        if: github.event_name == 'push' # 어떤 작업할때만 실행하겠다. 팀 단위 작업이면 pullRequest 일 듯
        uses: appleboy/ssh-action@master
        with: #아래 값들은 보여지면 안되므로 깃허브 세팅 -> 시크릿 액션즈에 저장해두고 사용
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /home/ubuntu/deploy/back/backup
            find /home/ubuntu/deploy/back/backup -name "backup-*.jar" -mtime +3 -delete
            if [ -f /home/ubuntu/deploy/back/*jar ]; then
              mv /home/ubuntu/deploy/back/*jar /home/ubuntu/deploy/back/backup/backup-$(date +%Y%m%d%H%M%S).jar
            fi

      - name: Deploy Boot App To EC2
        if: github.event_name == 'push'
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/deploy/back/"
          strip_components: 2 #맨앞에서 부터 /기준으로 몇개의 경로를 날릴것인지
      
      - name: Restart Container
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/deploy
            docker compose restart api
            sleep 50
            sudo cp /home/ubuntu/deploy/front/maintenence/index_tmp.html /home/ubuntu/deploy/front/dist/index.html
            sudo rm /home/ubuntu/deploy/front/maintenence/index_tmp.html
            docker compose restart web
            echo "정상모드 복원 완료"
